CREATE TABLE IF NOT EXISTS customers(
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(256) NOT NULL,
	birth VARCHAR(256) NOT NULL,
	email VARCHAR(256) NOT NULL,
	post_num VARCHAR(256) NOT NULL,
	adress VARCHAR(256) NOT NULL,
	num_of_buy INTEGER NOT NULL,
	last_buy VARCHAR(256) NOT NULL,
	PRIMARY KEY (id)
);

